Traceback (most recent call last):
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/shappiron/anaconda3/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/shappiron/anaconda3/lib/python3.9/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from lifelines.fitters import ParametricUnivariateFitter

Tmax = T.max()

class GompertzFitter(ParametricUnivariateFitter):
    # parametrization as above
    _fitted_parameter_names = ['A_', 'b_']

    def _cumulative_hazard(self, params, times):
        A_, b_ = params
        return A_ * (np.expm1(times * b_ / Tmax))

ggf = GompertzFitter()
ggf.fit(T, E)

ggf.print_summary()
ax = ggf.plot_survival_function(figsize=(8,5))
ax = KaplanMeierFitter().fit(T, E).plot(ax=ax, ci_show=False)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [15][0m, in [0;36m<cell line: 14>[0;34m()[0m
[1;32m     11[0m         [38;5;28;01mreturn[39;00m A_ [38;5;241m*[39m (np[38;5;241m.[39mexpm1(times [38;5;241m*[39m b_ [38;5;241m/[39m Tmax))
[1;32m     13[0m ggf [38;5;241m=[39m GompertzFitter()
[0;32m---> 14[0m ggf[38;5;241m.[39mfit(T, [43mE[49m)
[1;32m     16[0m ggf[38;5;241m.[39mprint_summary()
[1;32m     17[0m ax [38;5;241m=[39m ggf[38;5;241m.[39mplot_survival_function(figsize[38;5;241m=[39m([38;5;241m8[39m,[38;5;241m5[39m))

[0;31mNameError[0m: name 'E' is not defined
NameError: name 'E' is not defined

